### ISSUE TITLE
👉🏻 REQUEST: Skeleton Loading on Preview Page.

### ISSUE THREAD

**Issue by wh0sumit** [DunoLabs/invoicetor-landing#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

When there is no data on the editor page, the preview page displays an empty preview.

### Describe the solution you'd like

when there is no data present on the invoice, we can display a skeleton loading. 

![image](https://user-images.githubusercontent.com/76095902/181120604-dcea6499-01b0-4ae9-a66b-531368722855.png)

**Comment by Ninjavin** [comment]
Hey. I can take this issue.

**Comment by aadilkhalifa** [comment]
Hi. Can I work on this?

**Comment by wh0sumit** [comment]
Hello @aadilkhalifa, 

I'll assign this issue to you, but first It would be great if you could define your approach to building this feature!

**Comment by aadilkhalifa** [comment]
In [Preview.jsx](https://github.com/DunoLabs/invoicetor-landing/blob/main/src/components/Organism/Preview/Preview.jsxl), I'm thinking of comparing the invoice object state with that of an empty invoice object. 

If found to be the same, ie. no details have been added, display a skeleton loading similar to the one above with a message "Please enter details in the Editor tab to preview the invoice."

If the user has added details, display the invoice normally.

**Comment by aadilkhalifa** [comment]
Hi @wh0sumit 

I've worked on this and made a PR.
[Link to PR](https://github.com/DunoLabs/invoicetor-landing/pull/34)

Open to any feedback.

**Comment by wh0sumit** [comment]
Hey @aadilkhalifa, we're using chakra UI to create our UI and there is a skeleton component present, so there will be no need to add the external package to implement this feature. 

Try to implement it in ChakraUI and then push the changes!

**Comment by aadilkhalifa** [comment]
Hey @wh0sumit. Thanks for pointing it out.

I've replaced the loading skeleton with the chakra UI component.

**Comment by wh0sumit** [comment]
Yes, I have seen it, one of our maintainers will review it and we'll get back to you soon!

**Comment by wh0sumit** [comment]
@aadilkhalifa, your changes are good, can you create a skeleton structure similar to the invoice we're developing: a preview file needs to be copied and then the data has to be changed with the skeleton loaded. You can also create a separate component within the folder for skeleton loading for preview!

**Comment by aadilkhalifa** [comment]
Hi @wh0sumit. I've updated the PR with the suggested change.
