### ISSUE TITLE
🐛 Bug: This has ruined my system. Are you hacking or what ?  Stealing data ? What are you trying to achieve completely ruin the system. Stay away everyone

### ISSUE THREAD

**Issue by datageek1122** [DunoLabs/invoicetor-landing#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Ruined my system, hacking may be

### Expected Behavior

To run normal

### Steps To Reproduce

Take them off

### Environment

```markdown
- Platform:windows
- OS:
- Browser:
- Version:
- Screen Size(in inch)(Approx):
```

### Anything else?

You should shut this

**Comment by wh0sumit** [comment]
The issue won't last more than 24 hours because I don't find it suitable, so please describe it thoroughly in the meantime, so we can discuss more about it!
