### ISSUE TITLE
👉🏻 REQUEST: Update Documentations !

### ISSUE THREAD

**Issue by wh0sumit** [DunoLabs/invoicetor-landing#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

A lack of proper documentation is preventing users, other developers, designers, and open-source contributors from getting to know more about the project. 

### Describe the solution you'd like

It would be great if we could create a proper readme file and other documents for the project so that anyone can learn more about it and contribute easily.

**Comment by snehafarkya** [comment]
Hey! Would love to work on the documentation! Assign this to me and wait for the best part😄

**Comment by wh0sumit** [comment]
we would love your help with the documentation part!

while documenting the Invoicetor, there is a lot to do: we can schedule a meeting on HEKORS discord and discuss it there 

I am assigning this issue to you!

**Comment by atinder11** [comment]
I would love to work on this please assign me with this.

**Comment by tmsagarofficial** [comment]
I would be very happy to contribute for this repo pls get in touch or reply to this message.

**Comment by wh0sumit** [comment]
Hey @atinder11 & @tmsagarofficial, this issue has been already assigned to @snehafarkya !

FYI: We will soon be raising some issues, so be sure to star this project and watch it so that you receive notifications as soon as new issues are raised 🤍
