### ISSUE TITLE
👉🏻 REQUEST: Made scroll back to top button smooth

### ISSUE THREAD

**Issue by AnshuPathak-88825** [DunoLabs/invoicetor-landing#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

when we add this feature it made better user experience

### Describe the solution you'd like

Required to made scroll smooth
![Screenshot (392)](https://user-images.githubusercontent.com/78332454/194000652-3cfa556a-cc54-48a5-a6aa-34d46784cbed.png)

**Comment by AnshuPathak-88825** [comment]
pls assign me this issue with hacktoberfest label @wh0sumit

**Comment by Ankita-278** [comment]
pls assign this issue to me?

**Comment by wh0sumit** [comment]
@AnshuPathak-88825  & @Ankita-278  could you both explain how to create a smooth scrolling effect in simple words??

**Comment by AnshuPathak-88825** [comment]
@wh0sumit  Added smooth scrolling feature pls merge it

**Comment by wh0sumit** [comment]
Do not raise unnecessary pull requests, wait for maintainers to assign before submitting a PR. 

this is the wrong way to contribute. You should first learn [how to contribute](https://github.com/DunoLabs/invoicetor-landing/blob/main/CONTRIBUTING.md) if you're a beginner.

**Comment by wh0sumit** [comment]
I'll assign this issue to you, but first, you have to explain to me how to create a smooth scrolling effect in simple word.
