### ISSUE TITLE
👉🏻 REQUEST:  The website needs minor cosmetic changes in the User Interface

### ISSUE THREAD

**Issue by Abdulhussainjarif** [DunoLabs/invoicetor-landing#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

1. Wrong/Inconsistent bottomm-padding in the “Hacktoberfest pill” at the top of the navigation bar.
![image](https://user-images.githubusercontent.com/42992097/194022643-b7856077-e012-456a-aef5-37dce77af29f.png)

2. If we center-align these navigation-links the website will look more professional. This implies even when the website is in responsive state i.e. viewed on a tablet. 
![image](https://user-images.githubusercontent.com/42992097/194022926-246316e0-47f5-4e2a-9ead-35aeddbc1260.png)

3. Adding hover animations to the navigation bar navigation-links will improve accessibility issues and user experience.

4. Change “Scroll to top” button icon. Cannot predict the use of the button from this icon. Also we can add a scroll to top smooth scrolling animation.
![image](https://user-images.githubusercontent.com/42992097/194023393-0e246a85-2235-433d-a906-9d67a31df918.png)

### Describe the solution you'd like

As a User Experience designer, I can vouch on the fact that these changes can improve the overall experience of the user visiting the website.

1. The solution for the first issue is very basic, just add the correct bottom-padding to the "Hacktoberfest 2022" pill.

2.  A picture is worth a 1000 words, According to me this looks more professional and easier for the user to understand.
![image](https://user-images.githubusercontent.com/42992097/194026925-bc681d86-21db-460a-8bee-f53dcff99fda.png)

3. Add hover nav-links to improve accessibility. Also this hover effect passes the color contrast test 
![image](https://user-images.githubusercontent.com/42992097/194027694-8022ed49-6748-4683-9718-6dde3f962826.png)
![image](https://user-images.githubusercontent.com/42992097/194027829-0b26d2f0-1187-46e6-802a-2759237dc7ac.png)

 4. Icon similar to this will describe the functionality of the button much better 
![image](https://user-images.githubusercontent.com/42992097/194029126-e6b64e19-c767-4f7d-ad6a-8bc520a7056d.png)

### Additional context

As a User Experience designer and a frontend developer, I can easily solve these problem without any hassle. Please assign me these issues and I'll working on them right away.

**Comment by Abdulhussainjarif** [comment]
@wh0sumit please review these issues and assign this to me, so I can start working on it!! 

Also, could you add a "Hacktoberfest" label to this?

**Comment by wh0sumit** [comment]
Note: Please leave the fourth issue for a while, since the scrolling effect issue has already been created!
