### ISSUE TITLE
👉🏻 REQUEST:  Adding JSconfig File to Manage File Path

### ISSUE THREAD

**Issue by isiakaabd** [DunoLabs/invoicetor-landing#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/56041462/194487985-54daacba-adf6-4051-9cbb-d89db661a83a.png">

<img width="254" alt="image" src="https://user-images.githubusercontent.com/56041462/194488173-5a75b066-6664-4300-bca4-8568a97d65c4.png">

### Describe the solution you'd like

<img width="341" alt="image" src="https://user-images.githubusercontent.com/56041462/194489644-42a419a0-5877-48d9-babf-12f0e2970aab.png">

<img width="169" alt="image" src="https://user-images.githubusercontent.com/56041462/194489082-642b1678-5808-470f-9ec7-103303a8aa7d.png">

### Describe alternatives you've considered

by adding a JSConfig file to the root of the app and making our **src**  files as the base (or starting point for App). It helps the codebase to be neater and improve suggestions

### Additional context

https://code.visualstudio.com/docs/languages/jsconfig

**Comment by wh0sumit** [comment]
I'll assign this issue to you @isiakaab, you can start working on it! 

Happy Hacking ✌
