### ISSUE TITLE
👉🏻 REQUEST: What's new button can have minor color changes

### ISSUE THREAD

**Issue by Sakshy18** [DunoLabs/invoicetor-landing#37]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I feel in dark mode the What's new button is overshadowed and is not highlighted properly because of dark on dark 

### Describe the solution you'd like

one solution can be total contract ie white background with purple 400 in text
other solution can be adding white text to dark background in order to highlight the text and catch the eye

### Describe alternatives you've considered

![image](https://user-images.githubusercontent.com/84434398/194696291-99de17c8-d8ab-42ef-a570-e116d98e0cd9.png)
![image](https://user-images.githubusercontent.com/84434398/194696404-482d883a-4a9b-48cf-b9c7-c703306ba84e.png)

### Additional context

please let me know If I can start working on it

**Comment by kirtanchandak** [comment]
can I work on this issue ?

**Comment by wh0sumit** [comment]
@Sakshy18 Interesting, but I deliberately did so for some reason, so we're staying with the current button.

Thanks for raising this issue. I'll think about it, and if changing the UI is necessary, I'll reopen it again!
