### ISSUE TITLE
👉🏻 REQUEST:  Adding Progressive Web App (PWA) to the App

### ISSUE THREAD

**Issue by isiakaabd** [DunoLabs/invoicetor-landing#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

A PWA is a web application that apprehends the advantages of native and web applications. It delivers hardware features enveloped in the body of a cross-platform app that is quicker, more comfortable, and more inexpensive to create and support than a native app.  PWA is used by Facebook,  Linkedin, Instagram etc

### Describe the solution you'd like

<img width="290" alt="image" src="https://user-images.githubusercontent.com/56041462/194741355-af4c7ce9-e675-414c-a5d3-0ff3fb817d9f.png">

### BENEFITS OF PWA

1. **Working Offline**: PWAs can operate offline. Thus, when your network connection is unstable this type of app will still work as a clock, but in offline mode. Due to the built-in service workers, the features and information of the PWA are saved and cached. This allows accessing the PWA without downloading it, especially in terms of poor connectivity
2.  **Performance**: PWAs are loaded from a secure origin connection, i.e., using HTTPS. It helps reduce the app's load time and increases the app's loading time. 
3. **Fast Installation**:PWAs  are not required to be downloaded from a store; the user can save the app on a device with a click of a button. They can run as a standalone window instead of a browser, making them launchable from the user's home screen.
4. 

### Describe alternatives you've considered

[React PWA documentation](https://create-react-app.dev/docs/making-a-progressive-web-app/)

**Comment by isiakaabd** [comment]
@wh0sumit is this something I can proceed with?

**Comment by wh0sumit** [comment]
sorry for the late response @isiakaabd, it'll be great if we have a PWA for Invoicetor💜🤩

you can start working on this issue ✅ Happy Hacking ✨

**Comment by isiakaabd** [comment]
Ok, Thanks, I'm on it, please assign reviewer to my PRs🤲

**Comment by wh0sumit** [comment]
Currently, I am reviewing your PR, and one of our maintainers will review and merge it as soon as possible if there are no conflicts.

**Comment by isiakaabd** [comment]
@wh0sumit  I need a 512x512 image so I can generate the manifest logo.

**Comment by isiakaabd** [comment]
@wh0sumit  please don't forget the image

**Comment by wh0sumit** [comment]
It's been a busy week for me, so my reply is a bit late, but here is the 512 x 512 Image!

![Icon-512](https://user-images.githubusercontent.com/76095902/195679648-0de6395c-a31a-462e-a3c0-0383d045b5d7.png)

**Comment by Nerotool** [comment]
Send a message to NEROTOOL_ for help
