### ISSUE TITLE
🐛 Bug: Space is accepted as valid input in name field when adding an item.

### ISSUE THREAD

**Issue by reny-pacheco** [DunoLabs/invoicetor-landing#39]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Adding an item with `space` as value for `Item Name` is accepted which results to empty `Item Name`  when item is created.

**Screenshot:**

![image](https://user-images.githubusercontent.com/64537418/194748309-3f221872-6e16-40e6-afbe-db68a93870c5.png)

Preview Invoice:
![image](https://user-images.githubusercontent.com/64537418/194748345-e3252d7f-a27b-4cca-a965-a2bdb0020418.png)

### Expected Behavior

Show an error for empty fields.
Validate input values.

### Steps To Reproduce

1. Input spaces to Item Name.
2. Input valid value to Item Quantity.
3. Input valid value to Item Price.
4. Click Add Item.
5. Item is added but with EMPTY Item Name.

### Environment

```markdown
- Platform: Desktop
- OS: Windows 10
- Browser: Chrome
- Version: 105.0.5195.127
- Screen Size(in inch)(Approx): 24
```

**Comment by wh0sumit** [comment]
would you be interested in taking on this issue??

**Comment by reny-pacheco** [comment]
Yes. Thank you

**Comment by wh0sumit** [comment]
I've assigned this issue to you, you can now start contributing to it :) 

Happy Hacking 🌟

**Comment by isiakaabd** [comment]
@reny-pacheco  I would also suggest entire validations of all inputs, you could enter a non-email address and incorrect web link and it will work fine. since formik is used, Yup will be good for validations

**Comment by reny-pacheco** [comment]
Hi @isiakaabd , That's a very good suggestion :thumbsup: , I agree that using Yup will improve the validations for all inputs. But in my own opinion, adding Yup for validation is a feature, since it makes improvement to the app. Maybe someone should raise an issue regarding that. Thank you :smiley:.

**Comment by isiakaabd** [comment]
I would like to work on it, lets see how your implementation works for the input, aside the email and web links, others have the basic validation

**Comment by isiakaabd** [comment]
Ok, I will raise an issue about it now. Thanks
