### ISSUE TITLE
👉🏻 REQUEST:  Adding Yup to Formik for Validation

### ISSUE THREAD

**Issue by isiakaabd** [DunoLabs/invoicetor-landing#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Validations of Input fields using Formik, 

### Describe the solution you'd like

By Adding Formik, forms will be properly validated

### Describe alternatives you've considered

https://formik.org/docs/overview

**Comment by wh0sumit** [comment]
@isiakaabd you can start working on this issue, happy hacking ✨

**Comment by wh0sumit** [comment]
@isiakaabd, could you please share a list of the validations you're adding so we can get a better understanding?

**Comment by isiakaabd** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/56041462/195727253-128aedcb-b358-483b-b055-4b4da004f60b.png">

Most of the fields will have this validation, until these among others are validated, the save button will not function

**Comment by isiakaabd** [comment]
[link](https://63493e19321a7a22fdb15628--unique-tartufo-1dfc5f.netlify.app)

@wh0sumit  kindly check the preview, All the fields are required(and I think suggestions are welcome on that).

Merging this will create conflicts cos of other PR. It will be appreciated if the maintainer review as soon as possible and It also assist in winning prize in hactoberfest.


thank you

**Comment by wh0sumit** [comment]
After reviewing the dummy deployment, I have some suggestions: 

- For now, we can just leave the validations on the fields that are not mandatory to fill; 
I think adding validations to the name, email, and company name fields for the user and user's client would suffice. 

- It's not a good practice to hide the cursor pointer on the save button: you can show the validation errors for saving a invoice in toast, and the ctrl + s shortcut doesn't work. 

- Change the validation texts to make them more clear, some words start with capital letters and some do not: UI Changes!

**Comment by isiakaabd** [comment]
I will work on it and deploy it again, I will ensure the error message is capitalized
please don't forget to review our PRs

Thank you

**Comment by wh0sumit** [comment]
I'm working on it, and I'll merge your PR soon.

**Comment by isiakaabd** [comment]
[Link](https://formik-invoicetor.netlify.app )

Here is the revised link 

1. Added validation to the core part of the form and if required field not filled, on button clicked, it display error.

2.  Ctrl + save isn't working yet, it throws error especially if the required field isn't filled.

For your review @wh0sumit

**Comment by wh0sumit** [comment]
I'd like to discuss validation on our discord or if you don't have discord, we can discuss it on meet, share your email address so I can create a meeting invite, and finalize some things!

FYI: we are reviewing your other PRs as well :)

here is the link to join our Discord: https://discord.gg/hjdYdqas

**Comment by isiakaabd** [comment]
Thanks, I just joined the discord group
