### ISSUE TITLE
🐛 Bug: The email and website fields accept anything as input

### ISSUE THREAD

**Issue by komalioruganti** [DunoLabs/invoicetor-landing#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The fields "Client email", "Client website", "Your email","Your website" accept anyhting which is not necessarily a website url or email address as input. 

### Expected Behavior

The email and webite should take url and email as input. If anything else is entered, it should be shown as invalid.

### Steps To Reproduce

1. Add type attributes in input tag for email and website fields

### Environment

```markdown
- Platform: Desktop
- OS:Windows 
- Browser:Chrome
- Version:10
- Screen Size(in inch)(Approx):14
```

**Comment by komalioruganti** [comment]
Can I work on this issue?

**Comment by wh0sumit** [comment]
A new issue has already been created: we are adding validations to all the form fields!

**Comment by komalioruganti** [comment]
If any help is required I can contribute to it

**Comment by wh0sumit** [comment]
Start a discussion about issue #44 and collaborate with the contributor if you want to contribute in any manner!
