### ISSUE TITLE
🐛 Bug: Total doesn't round up decimal places 

### ISSUE THREAD

**Issue by freshairr** [DunoLabs/invoicetor-landing#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When calculating tax percentage in USD, the total amount doesn't round up.
![tax-before](https://user-images.githubusercontent.com/16641038/196489862-8dca883d-96aa-4cd8-bf41-9800dfaab3b5.PNG)

### Expected Behavior

The total should be rounded to the nearest 2 decimal places
![tax-after](https://user-images.githubusercontent.com/16641038/196489965-2854102e-3891-41dd-829b-1e9f824ae098.PNG)

### Steps To Reproduce

1. Change currency to USD
2. Add tax percent
3. Click 'Preview'

### Environment

```markdown
- Platform: Desktop
- OS: Windows 10
- Browser: Edge
- Version: 106.0.1370.42
- Screen Size(in inch)(Approx): 32"
```

**Comment by freshairr** [comment]
If I may, I would like to be assigned to this!

**Comment by wh0sumit** [comment]
Hey, I'll assign this issue to you, you can start working :)
