### ISSUE TITLE
Option to crop the signature image before uploading.

### ISSUE THREAD

**Issue by wh0sumit** [DunoLabs/invoicetor-landing#7]
When uploading the Signature Image, the user can crop the image and then upload it !

we can use packages called : [react-image-crop](https://www.npmjs.com/package/react-image-crop) to implement this task.

**Comment by vr513** [comment]
Can I take this one?

**Comment by wh0sumit** [comment]
Yes, @vr513 I will assign you this issue 🙌 happy hacking 💜
